version: '3.9'

services:
    
  notes_postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=NotesDB
    ports:
      - "45432:5432"
    networks:
      - shared_notes_net
    volumes:      
      - postgres-data:/var/lib/postgresql/data

  notes_api:
    ports:
      - "10000:8080"
    networks:
      - shared_notes_net
    env_file:
      - env.api

  notes_web:
    ports:
      - "10100:80"
    networks:
      - shared_notes_net
    env_file:
      - env.web

networks:
  shared_notes_net:
    name: notes
    driver: bridge

volumes:
  postgres-data: