name: Docker Compose CI

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  docker:
    name: Build and Test Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker Compose is installed
        run: docker version && docker compose version

      - name: Build Docker Images
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml build

      - name: Start Docker Compose services
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml up -d

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:10000/health; then
              echo "API is up!"
              exit 0
            fi
            sleep 2
          done
          echo "API did not start in time" >&2
          exit 1

      - name: Run integration tests (if applicable)
        run: docker exec minesweeper_api dotnet test --logger trx --results-directory TestResults || true

      - name: Show container logs on failure
        if: failure()
        run: docker compose logs

      - name: Stop Docker Compose services
        run: docker compose down
